from . import sale_order
from . import account_move
from . import SaleAdvancePaymentInv
from . import stock_picking
from . import stock_move
from . import purchase_order
from . import stock_rule
from . import mrp_production
from . import project_task
from . import project
from . import sale_order_line
