{
    "name": "School Management",
    "version": "15.0.0.0.1",
    "category": "school management",
    "summary": "school Management for education",
    "author": "BizzAppDev",
    "website": "https://www.bizzappdev.com",
    "depends": ["base"],
    "data": [
        "security/ir.model.access.csv",
        "security/school_managemment_security.xml",
        "data/student_server_action.xml",
        "data/ir_sequence_data.xml",
        "data/ir_cron_data.xml",
        "wizard/school_student_wizards.xml",
        "view/school_student_view.xml",
        "view/school_student_sport_view.xml",
        "view/school_teacher_view.xml",
        "view/school_student_marks_view.xml",
        "view/school_config_settings_views.xml",
        "view/school_student_main_menu.xml",
    ],
    "installable": True,
    "license": "Other proprietary",
}
